FROM alpine:3.11 as builder

# Install dependencies
RUN apk add --update \
        # Build utilities
        cmake make g++ \
        boost-dev \
        # NB: Both C and C++ headers + libOpenCL required
        opencl-headers opencl-icd-loader-dev \
 && rm -rf /var/cache/apk/*

RUN wget https://www.khronos.org/registry/OpenCL/api/2.1/cl.hpp -O /tmp/cl.hpp \
 && echo "08034743b513512bb6ea3a1e9a59bdf1842d8199fccad73ac1b406a88d60f7e0  /tmp/cl.hpp" | sha256sum -c \
 && install -m 644 /tmp/cl.hpp /usr/include/CL/ \
 && rm /tmp/cl.hpp



# Copy source files in
COPY . /tmp/dopencl

# Build
RUN mkdir /tmp/dopencl/build \
 && cd /tmp/dopencl/build \
 && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/dopencl .. \
 && make -j$(nproc) \
 && make install \
 && mkdir /opt/dopencl/include \
 && cp -r /tmp/dopencl/dclasio/include/* /opt/dopencl/include \
 && install -D -m755 /tmp/dopencl/dopenclenv.sh /etc/profile.d/dopenclenv.sh

FROM alpine:3.11

# Install dependencies
RUN apk add --update \
        boost-program_options boost-system opencl-icd-loader \
 && rm -rf /var/cache/apk/*



# Final install
COPY --from=builder /opt/dopencl /opt/dopencl
COPY --from=builder /etc/profile.d/dopenclenv.sh /etc/profile.d/dopenclenv.sh
