FROM ubuntu:bionic AS builder

# Install dependencies
RUN apt-get update \
 && apt-get install --yes --no-install-recommends \
        # Build utilities
        cmake make g++ \
        # Required by dopencl/icdpp, dopencl/dclasio
        libboost-dev \
        # Required by dopencl/daemon
        libboost-program-options-dev \
        # Required by dopencl/dclasio
        libboost-system-dev libboost-log-dev \
        # Required by tests
        libboost-thread-dev libboost-test-dev \
        # Development utilities
        gdb nano clinfo git \
        # NB: Both C and C++ headers + libOpenCL required
        opencl-headers ocl-icd-opencl-dev

# OpenCL runtime for nvidia-docker. Based on the nvidia/opencl DockerHub image
# See https://gitlab.com/nvidia/container-images/opencl/blob/ubuntu18.04/runtime/Doc$
RUN mkdir -p /etc/OpenCL/vendors \
 && echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd
# nvidia-container-runtime
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

# Copy source files in
COPY . /tmp/dopencl

WORKDIR /tmp/dopencl
