FROM dopencl_alpine

# Install dependencies
RUN apk add --update \
    gcc musl-dev opencl-headers opencl-icd-loader-dev openssl-dev \
 && rm -rf /var/cache/apk/*



# Build sample program
COPY test_ca.c test_ca.c
RUN gcc -fopenmp -O3 -march=native -Wall -Wextra -DLEGACY_OPENCL_1_2 test_ca.c -o test_ca -lOpenCL -lcrypto

# The list of dOpenCL worker nodes must be given as an environment variable (comma separated hosts)
ENV DCL_NODES 192.168.1.234,192.168.1.243

# Run sample program on the given dOpenCL worker nodes
RUN printf '#!/bin/sh\n\
. /etc/profile.d/dopenclenv.sh\n\
echo "$DCL_NODES" | tr "," "\n" > dcl.nodes\n\
LD_PRELOAD=/opt/dopencl/lib/libdOpenCL.so ./test_ca 10240 500\n' > launchscript.sh \
 && chmod +x launchscript.sh
CMD ["/launchscript.sh"]
