FROM dopencl_ubuntu

# OpenCL runtime for nvidia-docker. Based on the nvidia/opencl DockerHub image
# See https://gitlab.com/nvidia/container-images/opencl/blob/ubuntu18.04/runtime/Dockerfile
RUN apt-get update && apt-get install -y --no-install-recommends \
        ocl-icd-libopencl1 \
 && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/OpenCL/vendors \
 && echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd

# nvidia-container-runtime
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

# Run worker program on the container (will require OpenCL inside, e.g. with nvidia-docker)
EXPOSE 25025 25125

# FIXME: Here it would be more practical to simply run dcld 0.0.0.0, but this doesn't work
# because dOpenCL assigns the workers process IDs based on the hostname
# (see CommunicationManagerImpl::create_process_id), so two workers
# both bound to 0.0.0.0 will colide. So use the container IP instead.
RUN printf '#!/bin/sh\n\
. /etc/profile.d/dopenclenv.sh\n\
BIND_IP=$(hostname -i)\n\
dcld "$BIND_IP"\n' > launchscript.sh \
 && chmod +x launchscript.sh
CMD ["/launchscript.sh"]
